#!/usr/bin/env bash
source "$PLUGIN_PATH/common/functions"
# Reset bash mode from importing the functions
set +exo pipefail
# Fail on equation failure
set -e

# Build redis-server docker image
docker pull redis:latest
