#!/usr/bin/env bash
source "$PLUGIN_PATH/common/functions"
# Reset bash mode from importing the functions
set +exo pipefail
# Fail on equation failure
set -e

APP="$1"

dokku redis:destroy $APP 1 # This indicates that this is being called from event
