#!/usr/bin/env bash
source "$(dirname $0)/../common/functions"
# Reset bash mode from importing the functions
set +exo pipefail
# Fail on equation failure
set -e

APP="$1"
REDIS_FLAG_PERSISTENCE_FILE="$DOKKU_ROOT/$APP/REDIS"
REDIS_CONTAINER_NAME="redis-$APP"

# Only start Redis if it is enabled
if [[ -f $REDIS_FLAG_PERSISTENCE_FILE ]]; then
    dokku_log_info1 "Preparing Redis for $APP..."

    # Link to app
    dokku docker-options:add "$APP" deploy,run "--link $REDIS_CONTAINER_NAME:redis"
    dokku_log_info1 "Redis container linked: $APP -> $REDIS_CONTAINER_NAME"

    # Create REDIS_URL env variable for library / connector autoconfiguration
    dokku_log_info1 "Creating Redis autoconfiguration environment variable"
    dokku config:set-norestart "$APP" "REDIS_URL=redis://redis:6379"
fi
