#!/bin/bash

APP="$1"

# Start the redis instance for this app, if one is not already running,
# And make a link. The 1 at the end is to indicate that this is being run from a build hook
dokku redis:start $APP 1
