#!/usr/bin/env bash
source "$(dirname $0)/../common/functions"
# Reset bash mode from importing the functions
set +exo pipefail
# Fail on equation failure
set -e

APP="$1"
REDIS_FLAG_PERSISTENCE_FILE="$DOKKU_ROOT/$APP/REDIS"
REDIS_CONTAINER_NAME="redis-$APP"

dokku docker-options:remove "$APP" deploy,run "--link $REDIS_CONTAINER_NAME:redis"
